name: Build VS Code IDE Companion Extension

on:
  pull_request:
    paths:
      - 'packages/vscode-ide-companion/**'

jobs:
  build:
    name: Build VS Code IDE Companion Extension
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Package VSIX
        working-directory: packages/vscode-ide-companion
        run: npm run package

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: vsix
          path: packages/vscode-ide-companion/*.vsix
